### ISSUE TITLE
Deploy vps not work 

### ISSUE THREAD

**Issue by MissPuTrick** [LazyDeveloperr/LazyPrincess#21]
root@ubuntu-s-1vcpu-1gb-sgp1-01:~/LazyPrincess# git clone https://github.com/MissPuTrick/LazyPrincess
fatal: could not create work tree dir 'LazyPrincess': No such file or directory
root@ubuntu-s-1vcpu-1gb-sgp1-01:~/LazyPrincess# cd
root@ubuntu-s-1vcpu-1gb-sgp1-01:~# git clone https://github.com/MissPuTrick/LazyPrincess
Cloning into 'LazyPrincess'...
remote: Enumerating objects: 608, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 608 (delta 4), reused 0 (delta 0), pack-reused 595
Receiving objects: 100% (608/608), 1.42 MiB | 3.07 MiB/s, done.
Resolving deltas: 100% (387/387), done.
root@ubuntu-s-1vcpu-1gb-sgp1-01:~# cd LazyPrincess
root@ubuntu-s-1vcpu-1gb-sgp1-01:~/LazyPrincess# python3 bot.py
Traceback (most recent call last):
  File "/root/LazyPrincess/bot.py", line 12, in <module>
    from database.ia_filterdb import Media
  File "/root/LazyPrincess/database/ia_filterdb.py", line 10, in <module>
    from info import DATABASE_URI, DATABASE_NAME, COLLECTION_NAME, USE_CAPTION_FILTER
  File "/root/LazyPrincess/info.py", line 15, in <module>
    API_ID = int(environ['API_ID', '7045071'])
  File "/usr/lib/python3.10/os.py", line 676, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/usr/lib/python3.10/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not tuple
root@ubuntu-s-1vcpu-1gb-sgp1-01:~/LazyPrincess#

**Comment by MissPuTrick** [comment]
> clone

![Screenshot_20230330_203348_Termius](https://user-images.githubusercontent.com/109542127/228853476-eec2199f-4a9f-4ba8-93ec-e7a1967ffbbe.jpg)

**Comment by vpcreatz** [comment]
Looks like u didn't install requirements. For installing requirements use command * pip3 install -U -r requirements.txt * without given star symbol.

**Comment by vpcreatz** [comment]
And also edit info.py that is also reason for that.
