### ISSUE TITLE
bot failed to start

### ISSUE THREAD

**Issue by Dev-Khrish** [LazyDeveloperr/LazyPrincess#22]
Apr 2 10:21:17 AM  ==> Starting service with 'python3 bot.py'
Apr 2 10:21:29 AM  Traceback (most recent call last):
Apr 2 10:21:29 AM    File "bot.py", line 12, in <module>
Apr 2 10:21:29 AM      from database.ia_filterdb import Media
Apr 2 10:21:29 AM    File "/opt/render/project/src/database/ia_filterdb.py", line 10, in <module>
Apr 2 10:21:29 AM      from info import DATABASE_URI, DATABASE_NAME, COLLECTION_NAME, USE_CAPTION_FILTER
Apr 2 10:21:29 AM    File "/opt/render/project/src/info.py", line 68, in <module>
Apr 2 10:21:29 AM      LAZY_AI_LOGS = int(environ.get("LAZY_AI_LOGS","")) #GIVE YOUR NEW LOG CHANNEL ID TO STORE MESSAGES THAT THEY SEARCH IN BOT PM.... [ i have added this to keep an eye on the users message, to avoid misuse of LazyPrincess ]
Apr 2 10:21:29 AM  ValueError: invalid literal for int() with base 10: ''

logs error from render bot failed to start

**Comment by Tanujairamchecked** [comment]
Add LAZY_AI_LOGS var with the value of your log channel id
